name: GitHub Contributors

on:
  schedule:
    - cron: '0 */12 * * *'  # Executar a cada 12 horas
  workflow_dispatch: {}  # Permite a execução manual

jobs:
  github-contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'gampiot-inc/Robok-IDE'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub Contributors
        id: get_contributors
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/contributors \
               -o contributors/contributors_github.json

      - name: Install Python and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip jq

      - name: Format Contributors Table
        run: |
          python3 contributors/logic/format_contributors.py

      - name: Upload Table
        uses: actions/upload-artifact@v4
        with:
          name: github-contributors-table
          path: contributors/CONTRIBUTORS_TABLE.MD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update GitHub Contributors Table
          body: By GitHub Actions to update the table of contributors
          commit-message: "chore: update github contributors table"
          committer: GitHub Actions <actions@github.com>
          branch: contributors-github/patch
